package com.pi.dahora.utils

import com.pi.dahora.Models.Requirement

class Requirements {
    fun loadRequirements(): List<Requirement> = listOf(
        Requirement(
            0,
            "XQDL",
            "18/05/2022",
            "18/05/2022",
            4.0,
            null,
            null,
            "XQDL School",
            "18/05/2022 14:39:33",
            null,
            null,
            1,
            null,
            "approved",
            null
        ),
        Requirement(
            1,
            "XQDL1",
            "19/05/2022",
            "19/05/2022",
            5.0,
            null,
            null,
            "XQDL School1",
            "19/05/2022 15:39:33",
            null,
            null,
            2,
            null,
            "denied",
            null
        ),
        Requirement(
            2,
            "XQDL2",
            "20/05/2022",
            "20/05/2022",
            6.0,
            null,
            null,
            "XQDL School2",
            "20/05/2022 16:39:33",
            null,
            null,
            3,
            null,
            "created",
            null
        ),
        Requirement(
            0,
            "XQDL",
            "18/05/2022",
            "18/05/2022",
            4.0,
            null,
            null,
            "XQDL School",
            "18/05/2022 14:39:33",
            null,
            null,
            1,
            null,
            "approved",
            null
        ),
        Requirement(
            1,
            "XQDL1",
            "19/05/2022",
            "19/05/2022",
            5.0,
            null,
            null,
            "XQDL School1",
            "19/05/2022 15:39:33",
            null,
            null,
            2,
            null,
            "denied",
            null
        ),
        Requirement(
            2,
            "XQDL2",
            "20/05/2022",
            "20/05/2022",
            6.0,
            null,
            null,
            "XQDL School2",
            "20/05/2022 16:39:33",
            null,
            null,
            3,
            null,
            "created",
            null
        ),
        Requirement(
            0,
            "XQDL",
            "18/05/2022",
            "18/05/2022",
            4.0,
            null,
            null,
            "XQDL School",
            "18/05/2022 14:39:33",
            null,
            null,
            1,
            null,
            "approved",
            null
        ),
        Requirement(
            1,
            "XQDL1",
            "19/05/2022",
            "19/05/2022",
            5.0,
            null,
            null,
            "XQDL School1",
            "19/05/2022 15:39:33",
            null,
            null,
            2,
            null,
            "denied",
            null
        ),
        Requirement(
            2,
            "XQDL2",
            "20/05/2022",
            "20/05/2022",
            6.0,
            null,
            null,
            "XQDL School2",
            "20/05/2022 16:39:33",
            null,
            null,
            3,
            null,
            "created",
            null
        ),
        Requirement(
            0,
            "XQDL",
            "18/05/2022",
            "18/05/2022",
            4.0,
            null,
            null,
            "XQDL School",
            "18/05/2022 14:39:33",
            null,
            null,
            1,
            null,
            "approved",
            null
        ),
        Requirement(
            1,
            "XQDL1",
            "19/05/2022",
            "19/05/2022",
            5.0,
            null,
            null,
            "XQDL School1",
            "19/05/2022 15:39:33",
            null,
            null,
            2,
            null,
            "denied",
            null
        ),
        Requirement(
            2,
            "XQDL2",
            "20/05/2022",
            "20/05/2022",
            6.0,
            null,
            null,
            "XQDL School2",
            "20/05/2022 16:39:33",
            null,
            null,
            3,
            null,
            "created",
            null
        ),
        Requirement(
            0,
            "XQDL",
            "18/05/2022",
            "18/05/2022",
            4.0,
            null,
            null,
            "XQDL School",
            "18/05/2022 14:39:33",
            null,
            null,
            1,
            null,
            "approved",
            null
        ),
        Requirement(
            1,
            "XQDL1",
            "19/05/2022",
            "19/05/2022",
            5.0,
            null,
            null,
            "XQDL School1",
            "19/05/2022 15:39:33",
            null,
            null,
            2,
            null,
            "denied",
            null
        ),
        Requirement(
            2,
            "XQDL2",
            "20/05/2022",
            "20/05/2022",
            6.0,
            null,
            null,
            "XQDL School2",
            "20/05/2022 16:39:33",
            null,
            null,
            3,
            null,
            "created",
            null
        ),


    )
}
